FROM gocd/gocd-agent:16.2.1

# Jimmy in the SSH keys
ENV GO_HOME /var/go
COPY ssh/ ${GO_HOME}/.ssh/
RUN chown -R go:go ${GO_HOME}/.ssh/


# Add in the docker client
ENV DOCKER_BUCKET get.docker.com
ENV DOCKER_VERSION 1.11.1
ENV DOCKER_SHA256 893e3c6e89c0cd2c5f1e51ea41bc2dd97f5e791fcfa3cee28445df277836339d

RUN set -x \
	&& curl -fSL "https://${DOCKER_BUCKET}/builds/Linux/x86_64/docker-$DOCKER_VERSION.tgz" -o docker.tgz \
	&& echo "${DOCKER_SHA256} *docker.tgz" | sha256sum -c - \
	&& tar -xzvf docker.tgz \
	&& mv docker/* /usr/local/bin/ \
	&& rmdir docker \
	&& rm docker.tgz \
	&& docker -v

# Ensure docker is runnable by the "go" user
RUN mv /usr/local/bin/docker /usr/local/bin/docker.bin
RUN echo '#!/bin/bash\nsudo docker.bin $@' >> /usr/local/bin/docker && chmod +x /usr/local/bin/docker
RUN echo "go ALL=(ALL) NOPASSWD: /usr/local/bin/docker.bin" >> /etc/sudoers.d/docker
